### ISSUE TITLE
Malformed arguments to node-thrift RPC methods leak memory, leave transport buffers in corrupted state

### ISSUE THREAD

**Issue by trxcllnt** [mapd/mapd-connector#24]
Hey guys, I ran into a bug with the node-thrift lib while working on [rxjs-mapd](https://github.com/graphistry/rxjs-mapd) and want to make you aware in case you can guard against it. You can see my solution [here](https://github.com/graphistry/rxjs-mapd/blob/bf88da285ebc32ee6528f596919c626efccaf7ee/src/client/bind.ts#L85), but it's only convenient because I wrap all the Thrift client calls in methods that return Observables. I'm not sure if this affects Thrift's browser JS implementation.

## :beetle: bug
  - [x] Operating System and version: All
  - [x] Browser and version: All
  - [ ] Steps to reproduce (including dashboard link): N/A
  - [x] Description of issue:

From [THRIFT-4225](https://issues.apache.org/jira/browse/THRIFT-4225):

If the arguments to a thrift client method are malformed, the transport throws an error while writing the arguments to its buffers. Unfortunately, the buffers aren't reset (as would happen in flush), and the next RPC call will fail if any values were already written. Additionally, the callback isn't dereferenced from the client's _reqs table, leaking memory.

**Comment by mLuby** [comment]
@trxcllnt thanks for the report! I [added a test based on your fix](https://github.com/mapd/mapd-connector/pull/25) that I expected would fail, but it passes so I'm unable to reproduce the bug. Is there any more you can tell is about how to trigger it?

**Comment by trxcllnt** [comment]
@mLuby sorry, I forgot to include an example. The bug surfaces when you pass any non-nullable values of different types than the Thrift signature defines. I was testing that my error-handling paths would correctly propagate the error and disconnect the client, so I passed an Object instead of a Number as the `first_n` arg to `sql_execute_gpudf`. Thrift encodes the args before `first_n`, then throws when it gets to the `first_n`. Since it doesn't clean up its internal buffers, my follow-up call to `disconnect` sends the args that _were_ successfully written in the `sql_execute_gpudf` call, and the server logs a weird message.

I think your test passes because Thrift's codegen [guards against null/undefined explicitly](https://github.com/graphistry/rxjs-mapd/blob/master/src/mapd/MapD.js#L1987). If you set `BAD_ARG = {}` in your test, then [this line](https://github.com/mapd/mapd-connector/pull/25/files#diff-3567b9e0bba6be6a99890040b298a975R200) should synchronously throw an error ([here if using `TJSONProtocol`](https://github.com/apache/thrift/blob/master/lib/nodejs/lib/thrift/json_protocol.js#L352), or [here if using `TBinaryProtocol`](https://github.com/apache/thrift/blob/master/lib/nodejs/lib/thrift/binary_protocol.js#L161)). You should be able catch that error if you surround [this call](https://github.com/mapd/mapd-connector/blob/develop/src/wrap-with-error-handling.js#L26) in a try/catch. Then, you should be able to reset the internal state of the `context`, like I did [here](https://github.com/graphistry/rxjs-mapd/blob/bf88da285ebc32ee6528f596919c626efccaf7ee/src/client/bind.ts#L97).
