### ISSUE TITLE
mapd-connector js not creating while building the node 8 v and npm 5 version

### ISSUE THREAD

**Issue by Richard-bizruntime** [mapd/mapd-connector#30]
## :beetle: If bug
  - [ ] Operating System and version:
  - [ ] Browser and version:
  - [ ] Steps to reproduce (including dashboard link):
  - [ ] Description of issue:

## :new: If feature request  
  - [ ] User story:
  - [ ] Specific requirements/functionality:
  - [ ] Mocks (if applicable):

**Comment by Richard-bizruntime** [comment]
Hi i am working on mapd front end rendering, while creating mapd-connector "https://github.com/mapd/mapd-connector/" its not creating the mapd-connector.js but Builded in successfuly.

**Comment by mLuby** [comment]
Hi @Richard-bizruntime two questions:
1. In [v2.0.0](https://github.com/mapd/mapd-connector/releases/tag/v2.0.0) `dist/mapd-connector.js` became `dist/browser-connector.js` and `dist/node-connector.js` What do you see in your `dist/`?
2. When you say the "image is not 100% correct", can you give more information about what you see and what's different from what you expect to see?

**Comment by Richard-bizruntime** [comment]
Thanks @mLuby  yes your Right,Right now i am creating the image response ,using browser-connector.js and node-connector.js but the image rendering not coming the real image it
s coming like a template..![vega](https://user-images.githubusercontent.com/17870476/28301190-66f02c76-6ba2-11e7-8f6c-8556c7d824aa.png)

**Comment by ghartsel** [comment]
This should work with necessary host & Vega file name changes, returning a PNG image.  (Might want to browser Inspect to see any console logging or exceptions.)

HTML:

```
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <title>MapD</title>
        <meta charset="UTF-8">
      </head>
      <body>
        <script src="js/thrift.js"></script>
        <script src="js/mapd.thrift.js"></script>
        <script src="js/mapd_types.js"></script>
        <script src="js/browser-connector.js"></script>
        <script src="js/vegaspec.js"></script>
        <script src="js/vegademo.js"></script>

        <script>
        document.addEventListener('DOMContentLoaded', init, false);
        </script>
      </body>
    </html>

```
JS calling renderVega() with Vega JSON spec:

```
    function init() {
      var vegaOptions = {}
      var connector = new MapdCon()
        .protocol("http")
        .host("my.host.com")
        .port("9092")
        .dbName("mapd")
        .user("mapd")
        .password("HyperInteractive")
        .connect(function(error, con) {
          con.renderVega(1, JSON.stringify(exampleVega), vegaOptions, function(error, result) {
            if (error)
              console.log(error.message);
            else {
              var blobUrl = `data:image/png;base64,${result.image}`
              var body = document.querySelector('body')
              var vegaImg = new Image()
              vegaImg.src = blobUrl
              body.append(vegaImg)
            }
          });
        });
    }

```

**Comment by Richard-bizruntime** [comment]
@ghartsel Thanks for your Response , I got the image but i have a 310 rows contain different latitude and longitude but the image is showing only for the one point only , i don't  know where i went wrong ,could you tell me where i need to change to get correct latitude and longitude image of vega. for the reference i attached my single point snap for this post..
![updatedoutputimage](https://user-images.githubusercontent.com/17870476/28352334-6e22234c-6c73-11e7-9394-1b2699889bb8.png)

**Comment by Richard-bizruntime** [comment]
So i cross validated my database its connecting or not using the (https://mapd.github.io/mapd-connector/docs/#queryasync) but its not working  i got this issue while using mapd-connector documentations 
![image](https://user-images.githubusercontent.com/17870476/28355985-f414f29e-6c83-11e7-87e3-f6257a4305b6.png)
![image](https://user-images.githubusercontent.com/17870476/28356122-80742f70-6c84-11e7-8bcf-d1d28a082edd.png) 
Please anyone tell me what was the issue in the Vega or mapd-connector ,Thanks

**Comment by mLuby** [comment]
@Richard-bizruntime are you able to share your code? If not could you please try running this example (point to wherever you have the browser-connector file) and let us know if you see the map result? If so, try changing to your connection and vega settings—hopefully that will let us isolate the problem to something in your vega spec.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MapD</title>
    <meta charset="UTF-8">
  </head>
  <body>
    <script src="../dist/browser-connector.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', init, false);
      function init() {
        var vegaOptions = {}
        var connector = new MapdCon()
        .protocol("http")
        .host("metis.mapd.com")
        .port("9092")
        .dbName("mapd")
        .user("mapd")
        .password("HyperInteractive")
        .connect(function(error, con) {
          con.renderVega(1, JSON.stringify(exampleVega()), vegaOptions, function(error, result) {
            if (error)
              console.log(error.message);
            else {
              var blobUrl = `data:image/png;base64,${result.image}`
              var body = document.querySelector('body')
              var vegaImg = new Image()
              vegaImg.src = blobUrl
              body.append(vegaImg)
            }
          });
        });
      }
      function exampleVega () {
        return {
          "width": 384,
          "height": 564,
          "data": [
            {
              "name": "tweets",
              "sql": "SELECT goog_x as x, goog_y as y, tweets_nov_feb.rowid FROM tweets_nov_feb"
            }
          ],
          "scales": [
            {
              "name": "x",
              "type": "linear",
              "domain": [
                -3650484.1235206556,
                7413325.514451755
              ],
              "range": "width"
            },
            {
              "name": "y",
              "type": "linear",
              "domain": [
                -5778161.9183506705,
                10471808.487466192
              ],
              "range": "height"
            }
          ],
          "marks": [
            {
              "type": "points",
              "from": {
                "data": "tweets"
              },
              "properties": {
                "x": {
                  "scale": "x",
                  "field": "x"
                },
                "y": {
                  "scale": "y",
                  "field": "y"
                },
                "fillColor": "blue",
                "size": {
                  "value": 3
                }
              }
            }
          ]
        }
      }
    </script>
  </body>
</html>
```
![download](https://user-images.githubusercontent.com/2483420/28389938-f5036a10-6c8c-11e7-98e4-561f7d16c397.png)

**Comment by Richard-bizruntime** [comment]
@mLuby Thank you for your Response, i got the image as per your suggestion then i have duplicate latitude and longitude data so the points all coming together in same location,now i figure out the data's duplicate ,now i can able to view my image, and one more think i am using less dataset so the image coming like small  picture.Thanks for your guidance.

**Comment by mLuby** [comment]
Great. Sounds like we can close this issue, but please re-open if you still need help.

**Comment by dwayneberry** [comment]
@Richard-bizruntime 
Its worth noting you do not need to convert your points to mercator projections like the example here.

You can use our conversion functions on lat and lon directly in the sql query

example:
```
SELECT conv_4326_900913_x(lon) as x,conv_4326_900913_y(lat) as y,tweets_nov_feb.rowid FROM tweets_nov_feb
```

**Comment by Richard-bizruntime** [comment]
Hi team i have to use geo map canvas using the Vega Rendering Api its supported for the Back-end rendering in the mapd database,if  its there please let me know.Thank you..

**Comment by Richard-bizruntime** [comment]
@dwayneberry  Thanks for the information , i can use the point marks in the PNG its working fine if i use the squre ,rectangle in the marks shape its not working , could you tell me how can i archive rectangle ,squire and hexagon shapes in the marks , and i got one Json Object from source example but its not working for the reference i attached the  query for you please have a look on it.
"SELECT rect_pixel_bin(conv_4326_900913_x(longitude)) as x,rect_pixel_bin(conv_4326_900913_y(latitude)) as y, FROM vega " 

for the Json Object 
{
          "width": 384,
          "height": 564,
          "data": [
            {
              "name": "tweets",
              "sql": "SELECT conv_4326_900913_x(Latitude) as x, conv_4326_900913_y(Longitude) as y, rowid FROM vega"
            }
          ],
          "scales": [
            {
              "name": "x",
              "type": "quantize",
              "domain": [
                -3650484.1235206556,
                7413325.514451755
              ],
              "range": ["#0d0887", "#2a0593", "#41049d", "#5601a4", "#6a00a8",
                "#7e03a8", "#8f0da4", "#a11b9b", "#b12a90", "#bf3984",
                "#cb4679", "#d6556d", "#e16462", "#ea7457", "#f2844b",
                "#f89540", "#fca636", "#feba2c", "#fcce25", "#f7e425", "#f0f921"
              ],
              "default": "#0d0887",
              "nullValue": "#0d0887"
            },
            {
              "name": "y",
              "type": "quantize",
              "domain": [
                -5778161.9183506705,
                10471808.487466192
              ],
              "range": ["#0d0887", "#2a0593", "#41049d", "#5601a4", "#6a00a8",
                "#7e03a8", "#8f0da4", "#a11b9b", "#b12a90", "#bf3984",
                "#cb4679", "#d6556d", "#e16462", "#ea7457", "#f2844b",
                "#f89540", "#fca636", "#feba2c", "#fcce25", "#f7e425", "#f0f921"
              ],
              "default": "#0d0887",
              "nullValue": "#0d0887"
            }
          ],
          "marks": [
            {
                "type": "symbol", 
                "from": {
                "data": "tweets"
              },
              "properties": {
                  "shape": "square",
                "x": {
                  "scale": "x",
                  "field": "x"
                },
                "y": {
                  "scale": "y",
                  "field": "y"
                },
                "fillColor": "blue",
                "size": {
                  "value": 10
                }
              }
            }
          ]
        }
i got this exception : a mark of type "symbol" is unsupported.
Could you tell me how can i archive different shape in the marks fields ,Thanks.

**Comment by mLuby** [comment]
1. Check that you're using 3.1.2 or later
```js
.connect((error, session) => session.getServerStatus(console.log))
// look for something like version: "3.1.2-20170719-9b89178"
```
2. your scales should have ranges of numeric arrays and should not specify default or nullValue colors.
3. marks should not use size property. Instead use width and height properties with numeric values in pixels.

**Comment by Richard-bizruntime** [comment]
@mLuby  Thank for the response, my mapd version 3.1.1. version so its not working,Then i have a another query regarding the Canvas binding, i have geo map based PNG image rendering from Vega,Then i converted the image to canvas for rendering the Pixel size of the image while Click Event occur, Now We can able to bind the same co-ordinate Canvas image with any geo map Canvas Right, i searched  in the forum most of the geo map  taking data from either geo co-ordinate or geo-json, but in my case i don’t have such kind of data what i have to do bind Canvas with geo canvas, could you give any idea, regarding such scenario,Thanks Advanced.
