### ISSUE TITLE
Placing mapd-connector on the server and still using it with mapd-crossfilter

### ISSUE THREAD

**Issue by rmi7** [mapd/mapd-connector#34]
If I were to put `mapd-connector` on the server (node.js), but still want to use it with `mapd-crossfilter` (in the browser).

Hw would that work?

I've looked into it and can see that `mapd-connector` returns an instance of the `Connector` class.
And `mapd-crossfilter` expects this object as an argument to it's constructor. 

But how am I able to pass this instance from the server (with `mapd-connector`) to the browser (with `mapd-crossfilter`).

## what I really want to achieve

I want to catch all requests server-side and add a `WHERE <somefield> = <somevalue>` to every query, while still using `mapd-crossfilter` in the browser. 

**Any help on how to achieve this is much appreciated!**

**Comment by mLuby** [comment]
Hi @rmi7 good question:

You'll want to create an adapter object on the client that will expose two methods to CrossFilter:
- [`adapter.query(query, conQueryOptions, (error, result) => {…})`](https://github.com/mapd/mapd-crossfilter/blob/master/src/ResultCache.js#L91)
- [`adapter.getFields(table, (error, columnsArray) => {…})`](https://github.com/mapd/mapd-crossfilter/blob/master/src/CrossFilter.js#L122)

and then have those methods make calls to your server which invokes the actual Connector methods.

Does that make sense?

**Comment by rmi7** [comment]
Thanks for the quick reply @mLuby.

I will try out your suggestion on monday. Glad that there is a way to accomplish what I want.

will follow-up here with any progress so that other people having this issue got some info on how to do it.

**Comment by rmi7** [comment]
@mLuby I have two questions

# 1.
on the server (which will receive requests from multiple clients) would you suggest doing:

1. at boot: `new Connector()`.
  with every request:  `connect()` --> `execute query()` --> `disconnect()`
2. at boot: `new Connector()` --> `connect()`
  with every request: `query()`
3. at boot: nothing
with every request: `new Connector()` --> `connect()` --> `query()` --> `disconnect()` --> destroy `Connector` instance
4. something else? 

# 2. `conn.disconnect` callback error
I see that `conn.disconnect` returns a callback function with an error argument, or success. So how could there ever be an error returned in this callback, and what to do if it happens.

**Comment by mLuby** [comment]
For your first question I would suggest option 2, though those would all work. If you are planning to use backend rendering, then you'll want each client to have its own connection/session.

Regarding `.disconnect`, any errors it generates would necessitate re`connect`ing, so the errors can be ignored.

**Comment by mLuby** [comment]
@rmi7 I'm closing this issue but feel free to re-open if what I described doesn't work.

**Comment by rmi7** [comment]
So I set it all up, query is being sent to mapd instance, but all I get back from the mapd instance is something like:

```
processResults { row_set:
   { row_desc: [ [Object] ],
     rows: [],
     columns: [ [Object] ],
     is_columnar: true },
  execution_time_ms: [Int64 value:6 octets:00 00 00 00 00 00 00 06],
  total_time_ms: [Int64 value:7 octets:00 00 00 00 00 00 00 07],
  nonce: '1' }
queyr result [ { val: null } ]
```
either `null` or empty arrays for all my queries.

## the flow

So I created the adapter, and passed it to `crossfilter` in the browser.

Now crossfilter will send queries through the adapter to the server, on which I have the `mapd-connector` and I will pass on the query from the adapter to the actual connector on the server, like so:

```javascript
// called from route on server, db is initialized and connected mapd-connector
executeQuery(stmt, stmtOptions, callback) {
  db.query(stmt, stmtOptions, (err, result) => {
    if (err)  return callback(err)
    return callback(null, result)
  })
})
```

this function will return the error/result to the called route, which will return it back to the adapter in the browser, which will "return it to crossfilter"

but as said I am only getting back null or empty arrays in the above `db.query` call from the mapd instance.

## so my question is
Am I missing something?
