### ISSUE TITLE
Publish this module on npm

### ISSUE THREAD

**Issue by rmi7** [mapd/mapd-connector#39]
## :new: Publish this module on npm

It would be great if this module is published on npm so that it can be installed with `npm install` and added to `package.json` to keep track of the version in use.

Right now it's not possible and I need to `git clone` the repo and then do `npm install`.

**Comment by rmi7** [comment]
using "git url as dependency" for now, but still would be nice if it's in `npm`.

```json
"@mapd/connector": "git+https://mapd@github.com/mapd/mapd-connector.git#v3.0.0",
```

**Comment by clhenrick** [comment]
@micahstubbs what do you think about this? I think it would help us be able to use MapD in other JS frameworks and things like D3 Blocks / Observable.

**Comment by micahstubbs** [comment]
open questions for us:  

- [ ] do we prefer the
  - flat global namespace package name `mapd-connector` or 
  - the `@mapd/connector` npm account namespaced package name
?

- [ ] update immerse if we do decide to change the official package name to the flat `mapd-connector` name

**Comment by jrajav** [comment]
Put my chip in for `@mapd/connector`. Scoped packages will probably get more support going forward and are just more elegant for now.

**Comment by clhenrick** [comment]
thanks @micahstubbs for publishing. I have no preference over the naming convention.

**Comment by micahstubbs** [comment]
@jrajav maybe we do both? that global namespace is soooo much easier to remember and better for marketing our projects to other open source devs

**Comment by micahstubbs** [comment]
the global namespace approach also has the benefit of being able to match exactly the repo name on github as well. this consistency makes me happy, and probably has some value.

**Comment by domoritz** [comment]
Is there a timeline for this?

**Comment by micahstubbs** [comment]
@domoritz good question.  I'd really like to see @biovisualize @clhenrick and the dev team at MapD publish new releases to npm https://www.npmjs.com/package/mapd-connector

**Comment by clhenrick** [comment]
For now we will have to publish to `mapd-connector` instead of `@mapd/connector`. Will give it a go once I have the okay from the team.

**Comment by clhenrick** [comment]
Latest is now on NPM under `@mapd/connector`, and the npm version will now match the tagged version in this repo (once #94 has been merged).

https://www.npmjs.com/package/@mapd/connector

**Comment by clhenrick** [comment]
thanks for letting me know @micahstubbs, I'll look into making it public.

**Comment by clhenrick** [comment]
@micahstubbs try now: https://www.npmjs.com/package/@mapd/connector

**Comment by micahstubbs** [comment]
![screen shot 2018-07-20 at 3 03 44 pm](https://user-images.githubusercontent.com/2119400/43027246-2198d45e-8c2e-11e8-833e-80e2e0718201.png)
