### ISSUE TITLE
ERROR in ./build/thrift/node/mapd.thrift.js

### ISSUE THREAD

**Issue by ajoabraham** [mapd/mapd-connector#50]
Hello,

I'm not able to build, run the test, or use the connector.  When I run npm run build I get the following error:

ERROR in ./build/thrift/node/mapd_types.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./completion_hints_types in /home/anakin/mapd-connector/build/thrift/node
 @ ./build/thrift/node/mapd_types.js 13:30-65

Thanks!

**Comment by pgp44** [comment]
Having the same problem
