### ISSUE TITLE
add getCompletionHints

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd-connector#52]
## :new: feature request  
  - [ ] User story: as a developer, I'd like to be able to easily get autocomplete completion hints from **mapd-core**
  - [ ] Specific requirements/functionality:
  - [ ] Mocks (if applicable):

the backend endpoint is somewhat documented in this PR https://github.com/mapd/mapd-core/pull/142

**Comment by micahstubbs** [comment]
@mrblueblue @biovisualize would love advice on the best way to do then when you are back from 🎄 🎅 and have some cycles.

**Comment by micahstubbs** [comment]
<img width="1102" alt="screen shot 2017-12-26 at 11 03 06 am" src="https://user-images.githubusercontent.com/2119400/34362910-661f9026-ea2c-11e7-9730-9b13a747e7c1.png">

https://mapd.slack.com/archives/G7SEBKZ1P/p1514313743000221

**Comment by micahstubbs** [comment]
link 1 https://github.com/mapd/mapd-immerse/blob/master/src/services/mapd-con.js#L89
link 2 https://github.com/mapd/mapd-immerse/pull/2309/files#diff-d3a3e6a6f674d77308d7cb2fddb9fbf2R757

**Comment by micahstubbs** [comment]
useful reference: this PR shows how @biovisualize added a new endpoint https://github.com/mapd/mapd-connector/pull/41/files

**Comment by jrajav** [comment]
Closed in https://github.com/mapd/mapd-connector/pull/53
