### ISSUE TITLE
Fix mapd-connector to address the poor query performance on large array columns.

### ISSUE THREAD

**Issue by mythilimapd** [mapd/mapd-connector#61]
## :beetle: If bug
  - [ ] Operating System and version:
  - [ ] Browser and version:
  - [ ] Steps to reproduce (including dashboard link):
  - [ ] Description of issue:

## :new: If feature request  
  -  Fix mapd-connector to address the poor query performance on large array columns. 
  - [ ] Specific requirements/functionality:
  - [ ] Mocks (if applicable):

**Comment by biovisualize** [comment]
Closing as duplicates of #4068. Even if they are tasks on separate repos, I think it's better to track this work in a single place.

**Comment by domoritz** [comment]
@biovisualize What does #4068 refer to?
