### ISSUE TITLE
create a promise based version of getFields

### ISSUE THREAD

**Issue by clhenrick** [mapd/mapd-connector#65]
most methods of the connector API have an equivalent `Async` method that returns a promise. However the `getFields` method does not. To make the API consistent we should add a `getFieldsAsync` method.

There's also some speculation that the methods without `Async` are depreciated / out of date.

Additionally issue #15 points out there is a known bug in the `getFields` method.

**Comment by jrajav** [comment]
Closed by https://github.com/mapd/mapd-connector/pull/76
