### ISSUE TITLE
unavailable TCopyParams when trying to detect table column type?

### ISSUE THREAD

**Issue by theweaklink** [mapd/mapd-connector#74]
hi,

this question may be very simple: how can we import `TCopyParams` (and other Txxx objects) from `node-connector`. I can't seem to be able to run the following after connecting to mapd:
```
var copyParams = new TCopyParams();
con.detectColumnTypesAsync('table_data.csv', copyParams).then(res => console.log(res))
```
error message is `TypeError: TCopyParams is not a constructor`
I'm running on Node v8

thanks

**Comment by MarcBalaban** [comment]
Unfortunately node-connector encapsulates the Thrift Types for internal use, whereas browser-connector assigns the variables to the `window`

If you want access to the Thrift Types, I'd recommend doing an additional `require/import`:

eg: 

```
const Connector = require("@mapd/connector/dist/node-connector.js")
const Thrift = require("@mapd/connector/thrift/node/mapd_types.js")

console.log(new Thrift.TCopyParams())
*/---------------------
  {
    delimiter: null,
    null_str: null,
    has_header: null,
    quoted: null,
    quote: null,
    escape: null,
    line_delim: null,
    array_delim: null,
    array_begin: null,
    array_end: null,
    threads: null,
    table_type: 0,
    s3_access_key: null,
    s3_secret_key: null,
    s3_region: null,
    geo_coords_encoding: 0,
    geo_coords_comp_param: null
  }
---------------------*/
```

**Comment by theweaklink** [comment]
Thanks for the pointer to the correct import that was very helpful! 

In addition to adding the Thrift import in my node script, it did require to tweak the `src/helpers.js` in a similar way too actually:
```
const Thrift = require("../build/thrift/node/mapd_types.js")
export const convertObjectToThriftCopyParams = obj => new Thrift.TCopyParams(obj)
```
Otherwise `detectColumnTypesAsync()` would fail with error message relating to the dist version:
```
ReferenceError: TCopyParams is not defined at Object.convertObjectToThriftCopyParams (/var/task/node_modules/@mapd/connector/dist/node-connector.js:18153:4) at MapdCon.detectColumnTypes
```

Thanks a lot for pointing into the right direction.
