### ISSUE TITLE
Broken release?

### ISSUE THREAD

**Issue by domoritz** [mapd/mapd-connector#92]
In https://github.com/mapd/mapd-connector/tree/v3.0.0 the package.json says it's version 1.0. Shouldn't it be 3.0?

**Comment by clhenrick** [comment]
@domoritz sorry for the confusion around this. Connector wasn't originally published on NPM, and when it was published it wasn't clear that the version should match what was in `git tag`. 

I've just published the latest version to `4.0.1`: https://www.npmjs.com/package/@mapd/connector

We're now going to keep the repo version and npm version in sync, so there should be less confusion about the version from this point on.

**Comment by clhenrick** [comment]
Closing this for now, but feel free to reopen if there's any other confusion about the release. Thanks again @domoritz for bringing this to our attention.

**Comment by domoritz** [comment]
Sweet. Thank you!
