### ISSUE TITLE
Hanging query

### ISSUE THREAD

**Issue by domoritz** [mapd/mapd-connector#93]
A query that doesn't touch the data seems to hang:

```
select floor(2.0) from flights_donotmodify
```

<img width="956" alt="screen shot 2018-07-20 at 09 55 09" src="https://user-images.githubusercontent.com/589034/43015005-07ad37a4-8c03-11e8-8849-37fb67c67de4.png">

This is querying metis.

**Comment by tmostak** [comment]
@domoritz this will run every row right now for that dataset, projecting a large result set, and is overall quite inefficient. What's the timing if you run with `limit 1`?

**Comment by domoritz** [comment]
🤦‍♂️, of course. My SQL is pretty rusty. 

What I actually wanted was to write something like

`select floor(2.0)`

to test expressions but it raises `Error: Exception: Non-empty LogicalValues not supported yet`. 

`select floor(2.0) from flights_donotmodify limit 1` works fine.
